Repository YMedia8/YMD, pull requests merged in 2023-10, with the labels that each got.

#34 [FEAT] : ⚙️: detail페이지 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/datail/DetailAdapter.kt
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/hot/HotItemModel.kt
  app/src/main/res/layout/activity_detail2.xml
Labels: feature, design

#35 [FEATURE] Hot페이지
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/hot/HotFragment.kt
  app/src/main/java/com/example/ymd/hot/HotItemModel.kt
  app/src/main/res/layout/hot_item.xml
Labels: feature, merge

#36 [LITTLE_FIX] 비디오클릭시 디테일 액티비티(리사이클러뷰에 있는 아이템 가지고). 그 외 애니메이션 기능 완료
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/java/com/example/ymd/retrofit/Interface.kt
  app/src/main/java/com/example/ymd/search/SearchAdapter.kt
  app/src/main/java/com/example/ymd/search/SearchFragment.kt
  app/src/main/java/com/example/ymd/search/SearchItemModel.kt
  app/src/main/res/layout/search_image.xml
Labels: littleFix

#37 [FEAT] : Hot페이지
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/hot/HotFragment.kt
  app/src/main/res/layout/hot_item.xml
Labels: fix, feature, merge

#39 [FEAT] : ⚙️: Detail 데이터 받아오기
  app/build.gradle
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/search/SearchAdapter.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature, design

#42 [FEAT] : ⚙️: 공유 기능 추가
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/search/SearchItemModel.kt
  app/src/main/res/drawable/back.png
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_detail2.xml
Labels: feature, design

#43 [DESIGN][FEAT] 배경 블랙으로 변경, 카테고리별 검색 기능 완료, 데이터클래스 비디오ID추가
  app/src/main/java/com/example/ymd/retrofit/Interface.kt
  app/src/main/java/com/example/ymd/search/SearchAdapter.kt
  app/src/main/java/com/example/ymd/search/SearchFragment.kt
  app/src/main/java/com/example/ymd/search/SearchItemModel.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_information.xml
  app/src/main/res/drawable/ic_start.xml
  app/src/main/res/drawable/notifications.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_image.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature, merge, design, littleFix

#47 [FEAT] : ⚙️: 연관검색어 api연결
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/datail/DetailAdapter.kt
  app/src/main/java/com/example/ymd/datail/DetailModel.kt
  app/src/main/java/com/example/ymd/search/SearchAdapter.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/detail_item.xml
Labels: feature

#48 [FEAT]전체 카테고리별 검색 기능 완료
  app/src/main/java/com/example/ymd/search/SearchCategoryModel.kt
  app/src/main/java/com/example/ymd/search/SearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: feature, merge

#49 Feature/home channel
  app/src/main/java/com/example/ymd/home/HomeFragment.kt
  app/src/main/java/com/example/ymd/home/homeAdapter/CategoryVideoAdapter.kt
  app/src/main/java/com/example/ymd/home/homeAdapter/HomeAdapter.kt
  app/src/main/java/com/example/ymd/home/homeItemModel/HomeItemModel.kt
  app/src/main/res/layout/item_recycler_view_list.xml
Labels: merge

#50 [Fix] hot
  README.md
  app/src/main/res/layout/hot_item.xml
Labels: fix, design

#53 [FEAT] : ⚙️: 연관검색어 URL 연결
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/datail/DetailAdapter.kt
  app/src/main/java/com/example/ymd/datail/DetailModel.kt
  app/src/main/java/com/example/ymd/retrofit/Constants.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/detail_item.xml
Labels: feature

#54 [FEAT] 좋아요 누를 시 마이페이지 추가, 삭제 완료
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/Utils.kt
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/datail/DetailAdapter.kt
  app/src/main/java/com/example/ymd/mypage/MypageAdapter.kt
  app/src/main/java/com/example/ymd/mypage/MypageFragment.kt
  app/src/main/res/drawable/close.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/hot_item.xml
  app/src/main/res/layout/my_item.xml
Labels: feature, merge, littleFix

#56 [FEAT] : ⚙️: detail UI 수정
  app/src/main/java/com/example/ymd/datail/DetailAdapter.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/detail_item.xml
Labels: design

#57 [LITTLE_FIX][MERGE]좋아요 기능 픽스, 연관 동영상 픽스.
  app/src/main/java/com/example/ymd/datail/DetailActivity.kt
  app/src/main/java/com/example/ymd/mypage/MypageFragment.kt
  app/src/main/java/com/example/ymd/retrofit/Interface.kt
  app/src/main/java/com/example/ymd/search/SearchCategoryModel.kt
  app/src/main/res/drawable/yicon.png
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
Labels: fix, merge, design

#59 [DISIGN] 모든 파일 마무리
  app/src/main/java/com/example/ymd/hot/HotFragment.kt
Labels: feature, design

#60 Design/font
  app/src/main/java/com/example/ymd/home/homeAdapter/CategoryVideoAdapter.kt
  app/src/main/java/com/example/ymd/home/homeAdapter/HomeAdapter.kt
  app/src/main/java/com/example/ymd/mypage/MypageAdapter.kt
  app/src/main/res/font/dnfbit.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_hot.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_recycler_view_list.xml
  app/src/main/res/layout/my_item.xml
  app/src/main/res/values/themes.xml
Labels: design

#61 [bug] : 홈 화면에 Chanel 버그 수정완료
  app/src/main/java/com/example/ymd/home/HomeFragment.kt
  app/src/main/java/com/example/ymd/home/homeViewModel/CategoryChannelViewModel.kt
Labels: fix
