Repository YMedia8/YMD, pull requests merged in 2023-09, with the labels that each got.

#6 [DESIGN] : 🎨: 탭 레이아웃 추가 및 main디자인
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/ymd/HomeFragment.kt
  app/src/main/java/com/example/ymd/HotFragment.kt
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/MypageFragment.kt
  app/src/main/java/com/example/ymd/ViewPager2Adapter.kt
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/hot.xml
  app/src/main/res/drawable/mymedia.xml
  app/src/main/res/drawable/notifications.xml
  app/src/main/res/drawable/search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_hot.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/values/strings.xml
Labels: design

#8 Design/my video fragment
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/example/ymd/MyVideo_Fragment.kt
  app/src/main/res/drawable/play.png
  app/src/main/res/layout/my_item.xml
Labels: merge, design

#9 Design/detail fragment
  app/src/main/java/com/example/ymd/VideoDetailFragment.kt
  app/src/main/res/drawable/like.png
  app/src/main/res/drawable/like_size.xml
  app/src/main/res/drawable/share.png
  app/src/main/res/drawable/share_size.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: design

#10 [DESIGN] : Home_Fragment 디자인 추가
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/videoList/VideoAdapter.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recycler_view_category.xml
  app/src/main/res/layout/item_recycler_view_list.xml
  app/src/main/res/layout/item_recycler_view_list2.xml
  app/src/main/res/values/colors.xml
Labels: design

#13 [FIX] 마이페이지 및 아이콘 복구
  app/src/main/java/com/example/ymd/MyVideo_Fragment.kt
  app/src/main/java/com/example/ymd/videoList/VideoAdapter.kt
  app/src/main/res/drawable/ic_information.png
  app/src/main/res/drawable/ic_start.png
  app/src/main/res/layout/fragment_hot.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: bug, merge

#14 [DESIGN] : Home_Fragment 디자인 변경
  app/src/main/java/com/example/ymd/category/CategoryAdapter.kt
  app/src/main/res/drawable/ic_information.xml
  app/src/main/res/drawable/ic_start.xml
Labels: merge

#15 Design/home fragment3
  app/build.gradle
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/res/drawable/ic_information.png
  app/src/main/res/drawable/ic_start.png
  app/src/main/res/layout/fragment_search.xml
Labels: merge

#16 [FEAT] : ⚙️: 탭 레이아웃 검색항목 추가
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_search.xml
Labels: design

#17 [FEAT] : HotTopic retrofit 파일 생성
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/ymd/retrofit/HotTopicData/Item.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicData/MediaData.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicData/PageInfo.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicInterface.kt
  app/src/main/java/com/example/ymd/retrofit/YMDClient.kt
Labels: feature

#20 [FEAT] : ⚙️: 파일 정리
  .idea/misc.xml
  app/src/main/java/com/example/ymd/Home/HomeAdapter.kt
  app/src/main/java/com/example/ymd/Home/HomeFragment.kt
  app/src/main/java/com/example/ymd/HomeFragment.kt
  app/src/main/java/com/example/ymd/Hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/Hot/HotFragment.kt
  app/src/main/java/com/example/ymd/HotFragment.kt
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/Mypage/MypageAdapter.kt
  app/src/main/java/com/example/ymd/Mypage/MypageFragment.kt
  app/src/main/java/com/example/ymd/MypageFragment.kt
  app/src/main/java/com/example/ymd/Search/SearchFragment.kt
  app/src/main/java/com/example/ymd/Search/VideoAdapter.kt
  app/src/main/java/com/example/ymd/datail/DetailAdapter.kt
  app/src/main/java/com/example/ymd/videoList/SearchFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_hot.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
Labels: merge

#21 [FEAT] : ⚙️: 데이터 클래스 추가
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/retrofit/Categories/Categories.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicData/Item.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicData/MediaData.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicData/PageInfo.kt
  app/src/main/java/com/example/ymd/retrofit/HotTopicInterface.kt
  app/src/main/java/com/example/ymd/retrofit/Search/Search.kt
  app/src/main/java/com/example/ymd/retrofit/YoutubeData/VideoData.kt
Labels: feature

#23 [LITTLE_FIX] 검색기능 수정중
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/Search/SearchAdapter.kt
  app/src/main/java/com/example/ymd/Search/SearchFragment.kt
  app/src/main/java/com/example/ymd/Search/SearchItemModel.kt
  app/src/main/java/com/example/ymd/retrofit/Constants.kt
  app/src/main/java/com/example/ymd/retrofit/Interface.kt
  app/src/main/java/com/example/ymd/retrofit/YMDClient.kt
  app/src/main/res/layout/fragment_search.xml
Labels: littleFix

#24 [Feat] : api연결 후 테스트완료
  app/src/main/java/com/example/ymd/Home/HomeAdapter.kt
  app/src/main/java/com/example/ymd/Hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/Hot/HotFragment.kt
  app/src/main/java/com/example/ymd/MainActivity.kt
  app/src/main/java/com/example/ymd/Mypage/MypageAdapter.kt
  app/src/main/java/com/example/ymd/Search/SearchAdapter.kt
  app/src/main/java/com/example/ymd/Search/VideoAdapter.kt
  app/src/main/java/com/example/ymd/home/HomeAdapter.kt
  app/src/main/java/com/example/ymd/home/HomeFragment.kt
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/hot/HotFragment.kt
  app/src/main/java/com/example/ymd/hot/HotItemModel.kt
  app/src/main/java/com/example/ymd/mypage/MypageAdapter.kt
  app/src/main/java/com/example/ymd/mypage/MypageFragment.kt
  app/src/main/java/com/example/ymd/retrofit/Interface.kt
  app/src/main/java/com/example/ymd/retrofit/categories/Categories.kt
  app/src/main/java/com/example/ymd/retrofit/search/Search.kt
  app/src/main/java/com/example/ymd/retrofit/youtubeData/VideoData.kt
  app/src/main/java/com/example/ymd/search/SearchAdapter.kt
  app/src/main/java/com/example/ymd/search/SearchFragment.kt
  app/src/main/java/com/example/ymd/search/SearchItemModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_hot.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/hot_item.xml
  app/src/main/res/layout/hot_item2.xml
  app/src/main/res/layout/item_recycler_view_category.xml
Labels: feature, merge, design

#26 [FEAT] : Hot페이지 기능 추가 및 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/ymd/hot/HotAdapter.kt
  app/src/main/java/com/example/ymd/hot/HotFragment.kt
  app/src/main/res/layout/fragment_hot.xml
  app/src/main/res/layout/hot_item.xml
Labels: feature, design

#28 [FEAT] ⚙️:Feature/home most API 연동 기능 추가
  app/build.gradle
  app/src/main/java/com/example/ymd/home/HomeAdapter.kt
  app/src/main/java/com/example/ymd/home/HomeFragment.kt
  app/src/main/java/com/example/ymd/home/HomeItemModel.kt
  app/src/main/java/com/example/ymd/home/homeAdapter/HomeAdapter.kt
  app/src/main/java/com/example/ymd/home/homeViewModel/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feature

#30 [FEAT] 검색기능 완료
  app/src/main/java/com/example/ymd/search/SearchAdapter.kt
  app/src/main/java/com/example/ymd/search/SearchFragment.kt
  app/src/main/java/com/example/ymd/search/SearchItemModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/search_image.xml
Labels: feature, merge

#32 [FEAT] : 홈 화면에 카테 고리 데이터 추가
  app/src/main/java/com/example/ymd/home/HomeFragment.kt
  app/src/main/java/com/example/ymd/home/homeAdapter/HomeAdapter.kt
  app/src/main/java/com/example/ymd/home/homeItemModel/CategoryItemModel.kt
  app/src/main/java/com/example/ymd/home/homeItemModel/HomeItemModel.kt
  app/src/main/java/com/example/ymd/home/homeViewModel/CategoryViewModel.kt
  app/src/main/java/com/example/ymd/home/homeViewModel/HomeViewModel.kt
  app/src/main/java/com/example/ymd/retrofit/Interface.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_recycler_view_list.xml
  app/src/main/res/layout/item_recycler_view_list2.xml
Labels: feature
